import { Repeat, TrendingUp, TrendingDown, ArrowUpDown } from 'lucide-react';
import { formatCurrency, formatNumber } from '@/lib/calc';
import SortableTable from '@/components/SortableTable';

export default function SubrentalSection({ subrentalRows, ownedAvgUtilisation, periodDays, loading }) {
  const sortedByProfit = [...subrentalRows].sort((a, b) => b.netResult - a.netResult);

  const totalRevenue = subrentalRows.reduce((s, r) => s + r.revenue, 0);
  const totalCost = subrentalRows.reduce((s, r) => s + r.subrentalCost, 0);
  const totalNet = subrentalRows.reduce((s, r) => s + r.netResult, 0);
  const totalDays = subrentalRows.reduce((s, r) => s + r.rentalDays, 0);
  const avgUtil = subrentalRows.length > 0
    ? subrentalRows.reduce((s, r) => s + r.utilisation, 0) / subrentalRows.length
    : 0;

  const utilDiff = avgUtil - ownedAvgUtilisation;
  const maxNet = sortedByProfit.length > 0 ? Math.max(...sortedByProfit.map(r => Math.abs(r.netResult)), 1) : 1;

  const columns = [
    {
      key: 'name',
      label: 'Equipment',
      render: (row) => (
        <div className="flex items-center gap-2">
          <Repeat size={14} className="text-blue-500 shrink-0" />
          <span className="font-medium text-foreground truncate">{row.name}</span>
        </div>
      ),
    },
    {
      key: 'rentalCount',
      label: 'Times Rented',
      render: (row) => <span className="font-semibold">{row.rentalCount}</span>,
    },
    {
      key: 'rentalDays',
      label: 'Item-Days',
      render: (row) => formatNumber(row.rentalDays),
    },
    {
      key: 'revenue',
      label: 'Revenue',
      render: (row) => <span className="font-semibold">{formatCurrency(row.revenue)}</span>,
    },
    {
      key: 'subrentalCost',
      label: 'Cost',
      render: (row) => <span className="text-blue-600 dark:text-blue-400">{formatCurrency(row.subrentalCost)}</span>,
    },
    {
      key: 'netResult',
      label: 'Net Margin',
      render: (row) => (
        <div className="flex items-center gap-2">
          <span className={row.netResult >= 0 ? 'text-green-600 dark:text-green-400 font-semibold' : 'text-destructive font-semibold'}>
            {formatCurrency(row.netResult)}
          </span>
          {row.netResult >= 0 ? <TrendingUp size={12} className="text-green-500" /> : <TrendingDown size={12} className="text-destructive" />}
        </div>
      ),
    },
    {
      key: 'marginPercentage',
      label: 'Margin %',
      render: (row) => (
        <div className="flex items-center gap-2">
          <div className="w-16 h-1.5 bg-secondary rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all duration-500 ${row.marginPercentage >= 0 ? 'bg-green-500' : 'bg-destructive'}`}
              style={{ width: `${Math.min(100, Math.abs(row.marginPercentage))}%` }}
            />
          </div>
          <span className={`text-xs font-medium ${row.marginPercentage >= 0 ? 'text-green-600 dark:text-green-400' : 'text-destructive'}`}>
            {row.marginPercentage.toFixed(0)}%
          </span>
        </div>
      ),
    },
    {
      key: 'utilisation',
      label: 'Utilisation',
      render: (row) => (
        <div className="flex items-center gap-2">
          <div className="w-16 h-1.5 bg-secondary rounded-full overflow-hidden">
            <div
              className="h-full bg-blue-500 rounded-full transition-all duration-500"
              style={{ width: `${Math.min(100, row.utilisation)}%` }}
            />
          </div>
          <span className="text-xs font-medium text-blue-600 dark:text-blue-400">{row.utilisation.toFixed(0)}%</span>
        </div>
      ),
    },
  ];

  const summaryCards = [
    {
      label: 'Total Revenue',
      value: formatCurrency(totalRevenue),
      sub: 'Generated by sub-rentals',
    },
    {
      label: 'Sub-Rental Cost',
      value: formatCurrency(totalCost),
      sub: 'Paid to other rentals',
    },
    {
      label: 'Net Margin',
      value: formatCurrency(totalNet),
      sub: `${totalRevenue > 0 ? ((totalNet / totalRevenue) * 100).toFixed(0) : 0}% margin`,
      highlight: totalNet >= 0 ? 'positive' : 'negative',
    },
    {
      label: 'Utilisation vs Owned',
      value: `${avgUtil.toFixed(0)}%`,
      sub: `${utilDiff >= 0 ? '+' : ''}${utilDiff.toFixed(0)}% vs owned (${ownedAvgUtilisation.toFixed(0)}%)`,
      highlight: utilDiff >= 0 ? 'positive' : 'negative',
    },
  ];

  return (
    <div className="mt-8">
      {/* Section Header */}
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 rounded-lg bg-blue-500/10 flex items-center justify-center">
          <Repeat size={18} className="text-blue-500" />
        </div>
        <div>
          <h2 className="text-lg font-bold tracking-tight">Sub-Rental Performance</h2>
          <p className="text-xs text-muted-foreground">
            Profitability and usage of gear rented from other providers vs your owned inventory
          </p>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
        {summaryCards.map((s, i) => (
          <div key={i} className="bg-card rounded-lg border border-border p-4">
            <div className="text-xs text-muted-foreground uppercase tracking-wider mb-1">{s.label}</div>
            <div className={`text-xl font-bold ${s.highlight === 'positive' ? 'text-green-600 dark:text-green-400' : s.highlight === 'negative' ? 'text-destructive' : ''}`}>
              {s.value}
            </div>
            <div className="text-xs text-muted-foreground mt-0.5">{s.sub}</div>
          </div>
        ))}
      </div>

      {/* Table */}
      <div className="bg-card rounded-xl border border-border overflow-hidden">
        {loading ? (
          <div className="flex items-center justify-center py-12">
            <div className="w-8 h-8 border-3 border-secondary border-t-primary rounded-full animate-spin" />
          </div>
        ) : sortedByProfit.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-muted-foreground">
            <Repeat size={28} className="mb-2 opacity-40" />
            <p className="text-sm">No sub-rental equipment yet</p>
            <p className="text-xs mt-1">Mark equipment as sub-rental to track its performance here</p>
          </div>
        ) : (
          <SortableTable columns={columns} data={sortedByProfit} emptyMessage="No sub-rental equipment yet" />
        )}
      </div>

      {/* Insight Banner */}
      {sortedByProfit.length > 0 && (
        <div className="mt-3 flex items-start gap-2 text-xs text-muted-foreground bg-blue-500/5 border border-blue-500/20 rounded-lg p-3">
          <ArrowUpDown size={14} className="text-blue-500 shrink-0 mt-0.5" />
          <span>
            Sorted by net margin. High-margin items with high utilisation are the best candidates to purchase outright and eliminate rental costs.
            {totalDays > 0 && (
              <> Sub-rentals generated <span className="font-semibold text-foreground">{formatNumber(totalDays)} rental days</span> this period.</>
            )}
          </span>
        </div>
      )}
    </div>
  );
}